
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: gitops-backend

  frontend:
    image: httpd:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    container_name: gitops-frontend
    depends_on:
      - backend